name: yolov11_custom
network:
  # Đường dẫn tới ONNX model
  model_path: paper_ball.onnx
  
  # Input preprocessing
  input:
    input_layer_name: images
    input_shape: [1, 1, 640, 640]  # [batch, channels, height, width]
    normalization:
      mean: [ 0.0]
      std: [255.0]
      scale: 1.0
  # Output layers của YOLOv11
  output:
    - name: output0  # Thường là tên output của YOLO
      
# Compilation parameters
compilation:
  batch_size: 1
  
  # Optimization level
  optimization_level: 2  # 0-4, cao hơn = tối ưu hơn nhưng lâu hơn
  
  # Hailo chip target
  target_platform: hailo8l  # hoặc hailo8l, hailo15
  
# Quantization - chuyển từ FP32 sang INT8
quantization:
  calibration_dataset:
    path: ./calibration_images  # Thư mục chứa 50-100 ảnh đại diện
    batch_size: 8
  
  # Quantization parameters
  quantization_algorithm: symmetric  # hoặc 'asymmetric'
  
# Post-processing (optional)
postprocessing:
  nms:
    iou_threshold: 0.45
    score_threshold: 0.25
    max_output_boxes: 300